name: brics_currency_pipeline
version: 1.0.0
config-version: 2

profile: brics_currency_pipeline

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  brics_currency_pipeline:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: view
