FROM apache/airflow:2.10.5-python3.11

WORKDIR /opt/airflow

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY pipeline /opt/airflow/pipeline
COPY dags /opt/airflow/dags
